### ISSUE TITLE
do not work in variables or functions that use the export keyword

### ISSUE THREAD

**Issue by fengstats** [Simon-He95/vscode-tailwind-magic#2]
<img width="540" alt="image" src="https://github.com/Simon-He95/vscode-tailwind-magic/assets/48991003/26f78756-b10a-4299-a842-5c1b1f67134d">

**Comment by Simon-He95** [comment]
v0.0.78 has fixed

**Comment by fengstats** [comment]
> v0.0.78 has fixed

thx~
