### ISSUE TITLE
无法使用vscode-tailwind-magic

### ISSUE THREAD

**Issue by Y3coder** [Simon-He95/vscode-tailwind-magic#3]
保存时无法将w100%变成class="w-[100%]"
![PixPin_2024-02-22_23-38-04](https://github.com/Simon-He95/vscode-tailwind-magic/assets/122711240/9030bb16-bc78-47e2-be03-da22fc3678c1)

![20240222234110](https://github.com/Simon-He95/vscode-tailwind-magic/assets/122711240/449ce917-9644-40f2-b452-2d02469f809b)

配置如下
![image](https://github.com/Simon-He95/vscode-tailwind-magic/assets/122711240/b1047566-573b-48fe-9d9b-c136af7c43b2)

demo如下
[vue3-tailwindcss-pnpm.zip](https://github.com/Simon-He95/vscode-tailwind-magic/files/14386420/vue3-tailwindcss-pnpm.zip)

**Comment by Simon-He95** [comment]
你是`windows`吗

**Comment by Y3coder** [comment]
> 你是吗`windows`

是的，window版本是Windows 10 专业版22H2 19045.3930

**Comment by Simon-He95** [comment]
> > 你是吗`windows`
> 
> 是的，window版本是Windows 10 专业版22H2 19045.3930

<img width="949" alt="image" src="https://github.com/Simon-He95/vscode-tailwind-magic/assets/57086651/c35363b3-cbf6-4e27-b93a-5fb1ebdb9f35">
需要你看一下，当你写完保存时候，有没有什么错误日志，我使用你的demo，mac上是正常的，可能有路径或者哪里处理的有问题

**Comment by Y3coder** [comment]
> <img alt="image" width="949" src="https://private-user-images.githubusercontent.com/57086651/307498846-c35363b3-cbf6-4e27-b93a-5fb1ebdb9f35.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3NTQyMTMsIm5iZiI6MTcwODc1MzkxMywicGF0aCI6Ii81NzA4NjY1MS8zMDc0OTg4NDYtYzM1MzYzYjMtY2JmNi00ZTI3LWI5M2EtNWZiMWViZGI5ZjM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI0VDA1NTE1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxOTA5ODhkNDhjOGM5ZGI0ZDczMzE5ZDk1Y2MxMWJmYzEwMWFjMWFmYzBlNzM3ZGNiOGFkZmNjYmFjNjA0YzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ltJhU6zTRHv4psU9EHfTtZgH06P63ujwPpXIzarcU4I"> 需要你看一下，当你写完保存时候，有没有什么错误日志，我使用你的demo，mac上是正常的，可能有路径或者哪里处理的有问题

关于日志，我只找到如下：
2024-02-24 14:15:28.614 [info] ExtensionService#_doActivateExtension simonhe.vscode-tailwind-magic, startup: false, activationEvent: 'onStartupFinished'

**Comment by Simon-He95** [comment]
请升级到v0.0.81，测试一下功能是否正常:)

**Comment by Y3coder** [comment]
> 请升级到v0.0.81，测试一下功能是否正常:)

更新后功能正常，问题解决
