### ISSUE TITLE
不生效

### ISSUE THREAD

**Issue by xu-Aurora** [Simon-He95/vscode-tailwind-magic#4]
环境：
系统：window
vscode版本：1.85.1
操作流程：在div上输入w100然后保存，没有任何效果，例如<div w100></div>

说明：项目中已经使用tailwind插件，且有tailwind.config.js文件

**Comment by ylLin611** [comment]
看下你是不是装unocss插件了，把unocss禁用试下

**Comment by Simon-He95** [comment]
> 环境： 系统：window vscode版本：1.85.1 操作流程：在div上输入w100然后保存，没有任何效果，例如
> 
> 说明：项目中已经使用tailwind插件，且有tailwind.config.js文件

需要提供一个复现的demo

**Comment by Simon-He95** [comment]
由于缺少复现的repo，此issue暂时关闭，待提供复现repo，欢迎随时再打开
